// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class AiInfo {
  final String baseUrl;
  final String apiKey;
  final String modelName;
  final PlatformInt64 expiredTime;

  const AiInfo({
    required this.baseUrl,
    required this.apiKey,
    required this.modelName,
    required this.expiredTime,
  });

  @override
  int get hashCode =>
      baseUrl.hashCode ^
      apiKey.hashCode ^
      modelName.hashCode ^
      expiredTime.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AiInfo &&
          runtimeType == other.runtimeType &&
          baseUrl == other.baseUrl &&
          apiKey == other.apiKey &&
          modelName == other.modelName &&
          expiredTime == other.expiredTime;
}
