name: salary_report
description: "A new Flutter project."
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 0.0.2

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  riverpod: ^3.0.0
  flutter_riverpod: ^3.0.0
  toastification: ^3.0.3
  rust_lib_salary_report:
    path: rust_builder
  flutter_rust_bridge: 2.11.1
  file_selector: ^1.0.3
  syncfusion_flutter_charts: ^31.1.19
  isar_community: ^3.3.0-dev.2
  isar_community_flutter_libs: ^3.3.0-dev.2
  go_router: ^16.2.1
  path_provider: ^2.1.5
  logging: ^1.3.0
  shared_preferences: ^2.3.2
  docx_template_fork: ^0.5.0
  screenshot: ^3.0.0
  openai_dart: ^0.5.5
  loading_indicator: ^3.1.1
  open_file: ^3.5.10

  intl: any
  package_info_plus: ^9.0.0
  window_manager: ^0.5.1
  markdown_widget: ^2.3.2+8
dev_dependencies:
  build_runner: ^2.4.13
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  integration_test:
    sdk: flutter
  isar_community_generator: ^3.3.0-dev.2
  icons_launcher: ^3.0.2

flutter:
  uses-material-design: true

  fonts:
    - family: ph
      fonts:
        - asset: assets/fonts/AlibabaPuHuiTi-3-55-Regular.ttf
        - asset: assets/fonts/AlibabaPuHuiTi-3-75-SemiBold.ttf
          weight: 700

  assets:
    - assets/salary_report_template.docx
    - assets/salary_report_template_monthly.docx
    - assets/salary_report_template_multi_month.docx
    - assets/salary_report_template_quarterly.docx
    - assets/salary_report_template_annual.docx
    - assets/salary_report_template_multi_year.docx
    - assets/salary_report_template_multi_quarter.docx

icons_launcher:
  image_path: "../../aihr-icon.png"
  platforms:
    windows:
      enable: true
    linux:
      enable: true
    macos:
      enable: true
