// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// 工资记录
class SalaryRecord {
  final String name;
  final String department;
  final String position;
  final String attendance;
  final String salaryComponents;
  final String socialSecurityTax;
  final String netSalary;
  final String payrollDays;
  final String actualAttendanceDays;
  final String sickLeave;
  final String personalLeave;
  final String absence;
  final String truancy;
  final String performanceScore;

  const SalaryRecord({
    required this.name,
    required this.department,
    required this.position,
    required this.attendance,
    required this.salaryComponents,
    required this.socialSecurityTax,
    required this.netSalary,
    required this.payrollDays,
    required this.actualAttendanceDays,
    required this.sickLeave,
    required this.personalLeave,
    required this.absence,
    required this.truancy,
    required this.performanceScore,
  });

  @override
  int get hashCode =>
      name.hashCode ^
      department.hashCode ^
      position.hashCode ^
      attendance.hashCode ^
      salaryComponents.hashCode ^
      socialSecurityTax.hashCode ^
      netSalary.hashCode ^
      payrollDays.hashCode ^
      actualAttendanceDays.hashCode ^
      sickLeave.hashCode ^
      personalLeave.hashCode ^
      absence.hashCode ^
      truancy.hashCode ^
      performanceScore.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SalaryRecord &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          department == other.department &&
          position == other.position &&
          attendance == other.attendance &&
          salaryComponents == other.salaryComponents &&
          socialSecurityTax == other.socialSecurityTax &&
          netSalary == other.netSalary &&
          payrollDays == other.payrollDays &&
          actualAttendanceDays == other.actualAttendanceDays &&
          sickLeave == other.sickLeave &&
          personalLeave == other.personalLeave &&
          absence == other.absence &&
          truancy == other.truancy &&
          performanceScore == other.performanceScore;
}

/// 工资汇总信息
class SalarySummary {
  final BigInt totalRecords;
  final List<SalaryRecord> records;

  /// 汇总行数据，键为字段名或列索引，值为单元格内容
  final Map<String, String> summaryData;

  const SalarySummary({
    required this.totalRecords,
    required this.records,
    required this.summaryData,
  });

  @override
  int get hashCode =>
      totalRecords.hashCode ^ records.hashCode ^ summaryData.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SalarySummary &&
          runtimeType == other.runtimeType &&
          totalRecords == other.totalRecords &&
          records == other.records &&
          summaryData == other.summaryData;
}
