// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import '../salary_caculate/salary.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// 获取工资计算结果
///
/// # 参数
/// * `file_path` - Excel文件路径
///
/// # 返回值
/// 返回(错误信息, SalarySummary)元组，如果成功则错误信息为空
Future<(String, SalarySummary?)> getCaculateResult({
  required String filePath,
}) =>
    RustLib.instance.api.crateApiSalaryApiGetCaculateResult(filePath: filePath);
