spring:
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

  ai:
    openai:
      chat:
        options:
          model: ${CHAT_MODEL:Chat}
      embedding:
        options:
          model: ${EMBEDDING_MODEL:Embed}
        base-url: ${BASE_URL:http://127.0.0.1:9997}
      api-key: ${API_KEY:sk-X}
      base-url: ${BASE_URL:http://127.0.0.1:9997}